#-------------------------------
# General Site Settings
baseURL = "http://jsantosc.com/"
languageCode = "en-us"
title = "JSC"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 7

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 7 # Sets the number of items per page for older versions.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.footer]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  logo_dark = ""
  description = ""
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themselve.


#-------------------------------
# Hero Settings
[params.hero]
  enable = true
  hero__title = "James Santos-Calacat"
  hero__description = "I assist software engineering teams as a Software and Site Reliability Engineer by designing, developing, and monitoring backend systems, ensuring that applications and systems are reliable, scalable, and performant. Perpetual rookie student."
  hero__image = "" # You can add hero image. For example "/images/06.jpg"


#-------------------------------
# Blog Section Settings
[params.blog]
  enable = true
  blog__title = "Latest Posts"
  blog__description = ""



#-------------------------------
# Tag Section Settings
[params.tag]
  enable = true
  tag = "software-engineering" # To display the tag section, specify your favorite tag.


#-------------------------------
# Author Section Settings
[params.author_section]
  enable = true
  author__section__title = "Hello, my name is James. I’m a Site Reliability Engineer, Bodybuilder, and drummer."
  author__section__description = ""
  aurhor__section__button__text = "More About Me"
  aurhor__section__button__link = "/about"
  author__section__big__image = "/images/profile-photo-03.jpg"
  author__section__small__image = "/images/profile-photo-01.jpeg"
  author__section__image__alt = "James Santos-Calacat"


# Newsletter
[params.mailchimp]
  enable = false
  mailchimp__title = "Get interesting news"
  mailchimp__description = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
  mailchimp__identifier = "" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp__input__text = "Your email address"
  mailchimp__button__text = "Subscribe"
  mailchimp__background__image = "https://placehold.co/1920x1080"


#-------------------------------
# Footer Settings
[params.footer]
  footer__description = "You never know how strong you are, until being strong is your only choice"

# Social Links
[[params.social]]
icon = "fa-brands fa-linkedin"
name = "LinkedIn"
link = "https://www.linkedin.com/in/jsantosc/"

# Example of adding a new link to the footer section:
# [[params.social]]
#   icon = "fa-brands fa-mastodon"
#   name = "Mastodon"
#   link = "https://mastodon.social"

# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
#[params.contact]
#  form_id = "your@email.com" # Add your form_id

#-------------------------------
# Comment Section (Disqus)
[params.disqus]
  enable = false
  disqusShortname = "" # Add your shortname for Disqus Comment


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    ordered = false
    endLevel = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false